"""Canonical Theme Factory seed data used by local seeding commands."""

from __future__ import annotations

from datetime import datetime
from zoneinfo import ZoneInfo

KOLKATA_TZ = ZoneInfo("Asia/Kolkata")

THEME_SEED_THEMES = [
    {
        "theme_key": "motivation-monday",
        "theme_name": "Motivation Monday",
        "description": "Everyday Monday theme focused on momentum, encouragement, and a strong week start.",
        "theme_bucket": "everyday",
        "theme_type": "evergreen",
        "cultural_context": "global",
        "tone_style": "uplifting",
        "default_funny_pct": 18,
        "default_emotion_pct": 82,
        "default_audience": "working professionals",
        "default_visual_style": "minimal",
        "is_active": True,
        "priority": 90,
    },
    {
        "theme_key": "gratitude-tuesday",
        "theme_name": "Gratitude Tuesday",
        "description": "Everyday Tuesday theme for thank-you notes, appreciation, and grounded warmth.",
        "theme_bucket": "everyday",
        "theme_type": "evergreen",
        "cultural_context": "global",
        "tone_style": "warm",
        "default_funny_pct": 12,
        "default_emotion_pct": 88,
        "default_audience": "friends and colleagues",
        "default_visual_style": "minimal",
        "is_active": True,
        "priority": 88,
    },
    {
        "theme_key": "love-wednesday",
        "theme_name": "Love Wednesday",
        "description": "Everyday Wednesday theme centered on affection, care, and relationship warmth.",
        "theme_bucket": "everyday",
        "theme_type": "evergreen",
        "cultural_context": "global",
        "tone_style": "romantic",
        "default_funny_pct": 8,
        "default_emotion_pct": 92,
        "default_audience": "partners and loved ones",
        "default_visual_style": "elegant",
        "is_active": True,
        "priority": 86,
    },
    {
        "theme_key": "friendship-thursday",
        "theme_name": "Friendship Thursday",
        "description": "Everyday Thursday theme for friendship-led greetings and lighthearted connection.",
        "theme_bucket": "everyday",
        "theme_type": "evergreen",
        "cultural_context": "global",
        "tone_style": "warm",
        "default_funny_pct": 30,
        "default_emotion_pct": 70,
        "default_audience": "friends",
        "default_visual_style": "playful",
        "is_active": True,
        "priority": 84,
    },
    {
        "theme_key": "humor-friday",
        "theme_name": "Humor Friday",
        "description": "Everyday Friday theme tuned for wit, release, and end-of-week levity.",
        "theme_bucket": "everyday",
        "theme_type": "evergreen",
        "cultural_context": "global",
        "tone_style": "witty",
        "default_funny_pct": 60,
        "default_emotion_pct": 40,
        "default_audience": "friends and teams",
        "default_visual_style": "playful",
        "is_active": True,
        "priority": 82,
    },
    {
        "theme_key": "family-saturday",
        "theme_name": "Family Saturday",
        "description": "Weekend family-centered greetings with togetherness and affection.",
        "theme_bucket": "everyday",
        "theme_type": "evergreen",
        "cultural_context": "global",
        "tone_style": "heartfelt",
        "default_funny_pct": 14,
        "default_emotion_pct": 86,
        "default_audience": "family",
        "default_visual_style": "elegant",
        "is_active": True,
        "priority": 80,
    },
    {
        "theme_key": "reflection-sunday",
        "theme_name": "Reflection Sunday",
        "description": "Sunday theme for introspection, calm encouragement, and a gentle reset.",
        "theme_bucket": "everyday",
        "theme_type": "evergreen",
        "cultural_context": "global",
        "tone_style": "reflective",
        "default_funny_pct": 6,
        "default_emotion_pct": 94,
        "default_audience": "general audience",
        "default_visual_style": "minimal",
        "is_active": True,
        "priority": 78,
    },
    {
        "theme_key": "ramadan-month",
        "theme_name": "Ramadan Month",
        "description": "Occasion theme for Ramadan greetings, family connection, and community warmth.",
        "theme_bucket": "special",
        "theme_type": "calendar",
        "cultural_context": "ramadan",
        "tone_style": "heartfelt",
        "default_funny_pct": 5,
        "default_emotion_pct": 95,
        "default_audience": "family and community",
        "default_visual_style": "elegant",
        "is_active": True,
        "priority": 96,
    },
    {
        "theme_key": "holi-week",
        "theme_name": "Holi Week",
        "description": "Occasion theme for color, celebration, and playful spring greetings.",
        "theme_bucket": "special",
        "theme_type": "campaign",
        "cultural_context": "india",
        "tone_style": "festive",
        "default_funny_pct": 24,
        "default_emotion_pct": 76,
        "default_audience": "friends and family",
        "default_visual_style": "festive",
        "is_active": True,
        "priority": 94,
    },
    {
        "theme_key": "valentines-week",
        "theme_name": "Valentine's Week",
        "description": "Occasion theme for relationship, love, and affection-led campaigns.",
        "theme_bucket": "special",
        "theme_type": "campaign",
        "cultural_context": "global",
        "tone_style": "romantic",
        "default_funny_pct": 18,
        "default_emotion_pct": 82,
        "default_audience": "partners",
        "default_visual_style": "elegant",
        "is_active": True,
        "priority": 92,
    },
    {
        "theme_key": "india-trend-override",
        "theme_name": "India Trend Override",
        "description": "Current-event override theme for urgent India-led editorial trends.",
        "theme_bucket": "current_event",
        "theme_type": "news",
        "cultural_context": "india",
        "tone_style": "urgent",
        "default_funny_pct": 4,
        "default_emotion_pct": 96,
        "default_audience": "india audience",
        "default_visual_style": "editorial",
        "is_active": True,
        "priority": 100,
    },
]

THEME_SEED_SCHEDULES = [
    {
        "theme_key": "motivation-monday",
        "schedule_type": "weekly_recurring",
        "weekday_mask": ["monday"],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 90,
        "notes": "Default Monday recurring slot.",
    },
    {
        "theme_key": "gratitude-tuesday",
        "schedule_type": "weekly_recurring",
        "weekday_mask": ["tuesday"],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 88,
        "notes": "Default Tuesday recurring slot.",
    },
    {
        "theme_key": "love-wednesday",
        "schedule_type": "weekly_recurring",
        "weekday_mask": ["wednesday"],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 86,
        "notes": "Default Wednesday recurring slot.",
    },
    {
        "theme_key": "friendship-thursday",
        "schedule_type": "weekly_recurring",
        "weekday_mask": ["thursday"],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 84,
        "notes": "Default Thursday recurring slot.",
    },
    {
        "theme_key": "humor-friday",
        "schedule_type": "weekly_recurring",
        "weekday_mask": ["friday"],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 82,
        "notes": "Default Friday recurring slot.",
    },
    {
        "theme_key": "family-saturday",
        "schedule_type": "weekly_recurring",
        "weekday_mask": ["saturday"],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 80,
        "notes": "Default Saturday recurring slot.",
    },
    {
        "theme_key": "reflection-sunday",
        "schedule_type": "weekly_recurring",
        "weekday_mask": ["sunday"],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 78,
        "notes": "Default Sunday recurring slot.",
    },
    {
        "theme_key": "ramadan-month",
        "schedule_type": "date_range",
        "start_date": "2026-02-18",
        "end_date": "2026-03-19",
        "weekday_mask": [],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 96,
        "notes": "Example Ramadan campaign date range.",
    },
    {
        "theme_key": "holi-week",
        "schedule_type": "date_range",
        "start_date": "2026-03-01",
        "end_date": "2026-03-08",
        "weekday_mask": [],
        "month_mask": [],
        "region": "asia",
        "country": "india",
        "is_active": True,
        "priority": 94,
        "notes": "Example Holi campaign window.",
    },
    {
        "theme_key": "valentines-week",
        "schedule_type": "date_range",
        "start_date": "2026-02-07",
        "end_date": "2026-02-14",
        "weekday_mask": [],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 92,
        "notes": "Example Valentine's week campaign window.",
    },
]

THEME_SEED_OVERRIDES = [
    {
        "theme_key": "india-trend-override",
        "override_scope": "editorial",
        "start_at": datetime(2026, 8, 14, 0, 0, tzinfo=KOLKATA_TZ),
        "end_at": datetime(2026, 8, 16, 23, 59, 59, tzinfo=KOLKATA_TZ),
        "reason": "Sample India editorial override window for trend-led card operations.",
        "force_top_priority": True,
        "created_by": "seed",
    },
]
