"""Canonical Theme Factory seed data used by local seeding commands."""

from __future__ import annotations

THEME_SEED_THEMES = [
    {
        "theme_key": "motivation-monday",
        "theme_name": "Motivation Monday",
        "description": "Fresh-start motivation for a new week",
        "theme_bucket": "everyday",
        "theme_type": "evergreen",
        "cultural_context": "global",
        "tone_style": "uplifting",
        "default_funny_pct": 10,
        "default_emotion_pct": 70,
        "default_audience": "working professionals",
        "default_visual_style": "minimal",
        "is_active": True,
        "priority": 90,
    },
    {
        "theme_key": "gratitude-tuesday",
        "theme_name": "Gratitude Tuesday",
        "description": "Appreciation and thankfulness for everyday support",
        "theme_bucket": "everyday",
        "theme_type": "evergreen",
        "cultural_context": "global",
        "tone_style": "warm",
        "default_funny_pct": 5,
        "default_emotion_pct": 80,
        "default_audience": "friends and colleagues",
        "default_visual_style": "minimal",
        "is_active": True,
        "priority": 88,
    },
    {
        "theme_key": "love-wednesday",
        "theme_name": "Love Wednesday",
        "description": "Midweek affectionate and emotional love messages",
        "theme_bucket": "everyday",
        "theme_type": "evergreen",
        "cultural_context": "global",
        "tone_style": "heartfelt",
        "default_funny_pct": 5,
        "default_emotion_pct": 90,
        "default_audience": "partners and loved ones",
        "default_visual_style": "elegant",
        "is_active": True,
        "priority": 86,
    },
    {
        "theme_key": "friendship-thursday",
        "theme_name": "Friendship Thursday",
        "description": "Light and warm friendship content",
        "theme_bucket": "everyday",
        "theme_type": "evergreen",
        "cultural_context": "global",
        "tone_style": "playful",
        "default_funny_pct": 25,
        "default_emotion_pct": 70,
        "default_audience": "friends",
        "default_visual_style": "playful",
        "is_active": True,
        "priority": 84,
    },
    {
        "theme_key": "humor-friday",
        "theme_name": "Humor Friday",
        "description": "Funny and weekend-energy content",
        "theme_bucket": "everyday",
        "theme_type": "evergreen",
        "cultural_context": "global",
        "tone_style": "witty",
        "default_funny_pct": 60,
        "default_emotion_pct": 30,
        "default_audience": "friends and teams",
        "default_visual_style": "playful",
        "is_active": True,
        "priority": 82,
    },
    {
        "theme_key": "family-saturday",
        "theme_name": "Family Saturday",
        "description": "Family bonding, home, togetherness",
        "theme_bucket": "everyday",
        "theme_type": "evergreen",
        "cultural_context": "global",
        "tone_style": "warm",
        "default_funny_pct": 10,
        "default_emotion_pct": 85,
        "default_audience": "family",
        "default_visual_style": "elegant",
        "is_active": True,
        "priority": 80,
    },
    {
        "theme_key": "reflection-sunday",
        "theme_name": "Reflection Sunday",
        "description": "Calm reflection, peace, gratitude, reset",
        "theme_bucket": "everyday",
        "theme_type": "evergreen",
        "cultural_context": "global",
        "tone_style": "reflective",
        "default_funny_pct": 0,
        "default_emotion_pct": 85,
        "default_audience": "general audience",
        "default_visual_style": "minimal",
        "is_active": True,
        "priority": 78,
    },
    {
        "theme_key": "ramadan-month",
        "theme_name": "Ramadan Month",
        "description": "Respectful Ramadan greetings and reflection",
        "theme_bucket": "occasion",
        "theme_type": "calendar",
        "cultural_context": "islamic",
        "tone_style": "heartfelt",
        "default_funny_pct": 0,
        "default_emotion_pct": 95,
        "default_audience": "family and community",
        "default_visual_style": "elegant",
        "is_active": True,
        "priority": 96,
    },
    {
        "theme_key": "holi-week",
        "theme_name": "Holi Week",
        "description": "Holi celebration, colors, joy, togetherness",
        "theme_bucket": "occasion",
        "theme_type": "campaign",
        "cultural_context": "indian",
        "tone_style": "festive",
        "default_funny_pct": 20,
        "default_emotion_pct": 85,
        "default_audience": "friends and family",
        "default_visual_style": "festive",
        "is_active": True,
        "priority": 94,
    },
    {
        "theme_key": "valentines-week",
        "theme_name": "Valentine's Week",
        "description": "Romantic week-long greeting content",
        "theme_bucket": "occasion",
        "theme_type": "campaign",
        "cultural_context": "global",
        "tone_style": "romantic",
        "default_funny_pct": 5,
        "default_emotion_pct": 95,
        "default_audience": "partners",
        "default_visual_style": "elegant",
        "is_active": True,
        "priority": 92,
    },
    {
        "theme_key": "eid-celebration",
        "theme_name": "Eid Celebration",
        "description": "Eid greetings and celebration messages",
        "theme_bucket": "occasion",
        "theme_type": "calendar",
        "cultural_context": "islamic",
        "tone_style": "warm",
        "default_funny_pct": 5,
        "default_emotion_pct": 90,
        "default_audience": "family and community",
        "default_visual_style": "elegant",
        "is_active": True,
        "priority": 91,
    },
    {
        "theme_key": "diwali-week",
        "theme_name": "Diwali Week",
        "description": "Diwali lights, joy, prosperity, celebration",
        "theme_bucket": "occasion",
        "theme_type": "campaign",
        "cultural_context": "indian",
        "tone_style": "festive",
        "default_funny_pct": 15,
        "default_emotion_pct": 88,
        "default_audience": "friends and family",
        "default_visual_style": "festive",
        "is_active": True,
        "priority": 93,
    },
    {
        "theme_key": "friendship-day",
        "theme_name": "Friendship Day",
        "description": "Friendship Day greetings and appreciation",
        "theme_bucket": "occasion",
        "theme_type": "calendar",
        "cultural_context": "global",
        "tone_style": "playful",
        "default_funny_pct": 25,
        "default_emotion_pct": 75,
        "default_audience": "friends",
        "default_visual_style": "playful",
        "is_active": True,
        "priority": 89,
    },
    {
        "theme_key": "india-lpg-issue",
        "theme_name": "India LPG Issue",
        "description": "Public issue / awareness style theme for LPG-related discussion",
        "theme_bucket": "current_event",
        "theme_type": "news",
        "cultural_context": "indian",
        "tone_style": "awareness",
        "default_funny_pct": 0,
        "default_emotion_pct": 75,
        "default_audience": "india audience",
        "default_visual_style": "editorial",
        "is_active": True,
        "priority": 100,
    },
    {
        "theme_key": "iran-war-update",
        "theme_name": "Iran War Update",
        "description": "Serious current-event style theme",
        "theme_bucket": "current_event",
        "theme_type": "news",
        "cultural_context": "global",
        "tone_style": "serious",
        "default_funny_pct": 0,
        "default_emotion_pct": 70,
        "default_audience": "global audience",
        "default_visual_style": "editorial",
        "is_active": True,
        "priority": 99,
    },
    {
        "theme_key": "gold-price-watch",
        "theme_name": "Gold Price Watch",
        "description": "Market and money related trend theme",
        "theme_bucket": "current_event",
        "theme_type": "news",
        "cultural_context": "indian",
        "tone_style": "informative",
        "default_funny_pct": 0,
        "default_emotion_pct": 40,
        "default_audience": "india audience",
        "default_visual_style": "editorial",
        "is_active": True,
        "priority": 97,
    },
    {
        "theme_key": "india-trend-override",
        "theme_name": "India Trend Override",
        "description": "Generic current-events override for India-focused moments",
        "theme_bucket": "current_event",
        "theme_type": "news",
        "cultural_context": "indian",
        "tone_style": "editorial",
        "default_funny_pct": 0,
        "default_emotion_pct": 60,
        "default_audience": "india audience",
        "default_visual_style": "editorial",
        "is_active": True,
        "priority": 95,
    },
]

THEME_SEED_SCHEDULES = [
    {
        "theme_key": "motivation-monday",
        "schedule_type": "weekly_recurring",
        "weekday_mask": ["monday"],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 90,
        "notes": "Recurring Monday schedule.",
    },
    {
        "theme_key": "gratitude-tuesday",
        "schedule_type": "weekly_recurring",
        "weekday_mask": ["tuesday"],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 88,
        "notes": "Recurring Tuesday schedule.",
    },
    {
        "theme_key": "love-wednesday",
        "schedule_type": "weekly_recurring",
        "weekday_mask": ["wednesday"],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 86,
        "notes": "Recurring Wednesday schedule.",
    },
    {
        "theme_key": "friendship-thursday",
        "schedule_type": "weekly_recurring",
        "weekday_mask": ["thursday"],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 84,
        "notes": "Recurring Thursday schedule.",
    },
    {
        "theme_key": "humor-friday",
        "schedule_type": "weekly_recurring",
        "weekday_mask": ["friday"],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 82,
        "notes": "Recurring Friday schedule.",
    },
    {
        "theme_key": "family-saturday",
        "schedule_type": "weekly_recurring",
        "weekday_mask": ["saturday"],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 80,
        "notes": "Recurring Saturday schedule.",
    },
    {
        "theme_key": "reflection-sunday",
        "schedule_type": "weekly_recurring",
        "weekday_mask": ["sunday"],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 78,
        "notes": "Recurring Sunday schedule.",
    },
    {
        "theme_key": "ramadan-month",
        "schedule_type": "date_range",
        "start_date": "2026-02-18",
        "end_date": "2026-03-19",
        "weekday_mask": [],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 96,
        "notes": "Ramadan Month date-range schedule.",
    },
    {
        "theme_key": "holi-week",
        "schedule_type": "date_range",
        "start_date": "2026-03-09",
        "end_date": "2026-03-15",
        "weekday_mask": [],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 94,
        "notes": "Holi Week date-range schedule.",
    },
    {
        "theme_key": "valentines-week",
        "schedule_type": "date_range",
        "start_date": "2026-02-08",
        "end_date": "2026-02-14",
        "weekday_mask": [],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 92,
        "notes": "Valentine's Week date-range schedule.",
    },
    {
        "theme_key": "diwali-week",
        "schedule_type": "date_range",
        "start_date": "2026-11-08",
        "end_date": "2026-11-14",
        "weekday_mask": [],
        "month_mask": [],
        "region": None,
        "country": None,
        "is_active": True,
        "priority": 93,
        "notes": "Diwali Week date-range schedule.",
    },
]

THEME_SEED_OVERRIDES = []
